-- Power BI export model: expose dashboard-safe fields from modeled marts, not raw source tables.

select
    state_key,
    state_name,
    year,
    total_approved_loan_amount,
    loan_count,
    approval_amount_coverage_count,
    annual_average_unemployment_rate,
    unemployment_rate_yoy_change_pp,
    unemployment_rate_yoy_change_pp / 100.0 as unemployment_rate_yoy_change_pct,
    observed_month_count,
    observed_expected_month_count,
    unexpected_month_count,
    expected_month_count,
    publisher_omitted_month_count,
    missing_month_count,
    is_year_to_date,
    is_comparable_annual,
    annual_coverage_status,
    is_full_calendar_year,
    is_comparable_context,
    has_matched_establishment_population,
    bds_reference_date,
    establishment_count,
    establishment_entry_rate,
    establishment_exit_rate,
    loans_per_1000_establishments,
    approved_loan_dollars_per_establishment,
    has_lending_data,
    has_laus_data,
    has_business_dynamics_data,
    context_join_status
from {{ ref('mart_regional_business_health_annual_state') }}
where context_join_status = 'complete_context'
