let
    // Local CSV mode reads the stable latest export folder written by
    // make powerbi-refresh-local through pipelines.powerbi.export_contract.
    // In Power BI Desktop, edit ExportRoot to the Windows absolute path for this
    // repository's data/exports/powerbi folder if the relative path is not found.
    ExportRoot = "data/exports/powerbi",

    // Reuse one loader so every BI table has identical CSV parsing behavior:
    // UTF-8 input, comma delimiters, CSV quoting, and promoted scalar headers.
    ColumnTypes = [
        program_7a_loan_count = type number,
        paired_7a_coverage_count = type number,
        paired_7a_guaranteed_amount = type number,
        paired_7a_approval_amount = type number,
        paired_7a_coverage_rate = type number,

        approval_amount_coverage_count = type number,
        program_504_loan_count = type number,
        paired_504_coverage_count = type number,
        paired_504_third_party_dollars = type number,
        paired_504_approval_amount = type number,
        paired_504_coverage_rate = type number,
        known_504_third_party_to_sba_amount_rate = type number,
        bds_reference_date = type date,
        observation_date_basis = type text,
        approval_amount_basis = type text,
        reporting_lender_role = type text,
        has_matched_establishment_population = type logical,
        has_lending_data = type logical,
        has_laus_data = type logical,
        has_business_dynamics_data = type logical,
        is_known_industry = type logical,
        source_system = type text,
        source_dataset = type text,
        source_resource_name = type text,
        snapshot_validity_status = type text,
        latest_extracted_at_utc = type datetimezone,
        latest_ingestion_date = type date,
        latest_observation_date = type date,
        latest_row_count = type number,
        observed_snapshot_count = type number,
        is_latest_successful_snapshot = type logical,
        max_extract_age_days = type number,
        max_observation_age_days = type number,
        extract_age_days = type number,
        observation_age_days = type number,
        publication_reference_date = type date,
        publication_date = type date,
        publication_verified_date = type date,
        next_scheduled_release_date = type date,
        publication_source_url = type text,
        publication_cadence = type text,
        max_release_check_age_days = type number,
        release_check_age_days = type number,
        publication_status = type text,
        download_status = type text,
        freshness_reason = type text,
        annual_coverage_status = type text,
        calendar_period_status = type text,
        census_division = type text,
        census_region = type text,
        context_join_status = type text,
        final_pipeline_status_evidence = type text,
        freshness_status = type text,
        latest_run_status = type text,
        lender_key = type text,
        lender_name = type text,
        loan_program = type text,
        loan_program_key = type text,
        loan_program_name = type text,
        loan_status_group = type text,
        loan_status_group_label = type text,
        naics_description = type text,
        naics_key = type text,
        naics_sector_code = type text,
        naics_sector_name = type text,
        pipeline_run_ids = type text,
        raw_load_status = type text,
        state_abbr = type text,
        state_fips = type text,
        state_key = type text,
        state_name = type text,
        validation_status = type text,
        year_label = type text,
        is_comparable_annual = type logical,
        is_comparable_context = type logical,
        is_comparable_yoy = type logical,
        is_full_calendar_year = type logical,
        is_unknown = type logical,
        is_valid_current_code = type logical,
        is_year_to_date = type logical,
        coverage_evidence_as_of = type date,
        first_observed_approval_date = type date,
        last_observed_approval_date = type date,
        source_calendar_end = type date,
        source_calendar_start = type date,
        freshness_checked_at_utc = type datetimezone,
        loaded_at_utc = type datetimezone,
        annual_average_unemployment_rate = type number,
        approval_year = type number,
        approved_loan_amount_yoy_growth_pct = type number,
        approved_loan_dollars_per_establishment = type number,
        approved_loan_dollars_per_job_supported = type number,
        average_initial_interest_rate = type number,
        average_loan_size = type number,
        average_term_months = type number,
        charged_off_loan_count = type number,
        charged_off_loan_count_rate = type number,
        chargeoff_amount_rate = type number,
        comparable_prior_year_amount = type number,
        establishment_count = type number,
        establishment_entry_rate = type number,
        establishment_exit_rate = type number,
        expected_month_count = type number,
        fixed_interest_loan_count = type number,
        fixed_interest_loan_share = type number,
        gross_chargeoff_amount = type number,
        industry_approved_amount_share = type number,
        initial_interest_rate_coverage_count = type number,
        initial_interest_rate_coverage_rate = type number,
        interest_type_coverage_count = type number,
        jobs_supported_coverage_count = type number,
        jobs_supported_coverage_rate = type number,
        jobs_supported_per_1m_approved = type number,
        jobs_supported_per_loan = type number,
        lender_approved_amount_share = type number,
        lender_count = type number,
        lender_rank = type number,
        loan_count = type number,
        loan_status_sort_order = type number,
        loans_per_1000_establishments = type number,
        missing_month_count = type number,
        observed_month_count = type number,
        observed_expected_month_count = type number,
        unexpected_month_count = type number,
        program_approved_amount_share = type number,
        publisher_omitted_month_count = type number,
        sba_guaranteed_approval_amount = type number,
        seven_a_approved_loan_amount = type number,
        seven_a_sba_guarantee_rate = type number,
        status_group_approved_amount_share = type number,
        status_group_loan_count_share = type number,
        term_coverage_count = type number,
        term_coverage_rate = type number,
        third_party_dollars = type number,
        third_party_to_approved_amount_rate = type number,
        top_5_approved_loan_amount = type number,
        top_5_lender_share = type number,
        top_1_approved_loan_amount = type number,
        top_1_lender_share = type number,
        loan_count_yoy_growth_pct = type number,
        passed_check_count = type number,
        failed_check_count = type number,
        warning_check_count = type number,
        source_resource_count = type number,
        current_source_resource_count = type number,
        stale_or_unknown_source_resource_count = type number,
        total_approved_loan_amount = type number,
        total_initial_interest_rate = type number,
        total_jobs_supported = type number,
        total_term_months = type number,
        unemployment_rate_yoy_change_pct = type number,
        unemployment_rate_yoy_change_pp = type number,
        variable_interest_loan_count = type number,
        variable_interest_loan_share = type number,
        year = type number
    ],

    LoadCsv = (tableName as text) as table =>
      let
        Promoted = Table.PromoteHeaders(
            Csv.Document(
                File.Contents(ExportRoot & "/" & tableName & ".csv"),
                [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
            ),
            [PromoteAllScalars = true]
        ),
        Typed = Table.TransformColumnTypes(Promoted,
            List.Transform(
                List.Select(Table.ColumnNames(Promoted), each Record.HasFields(ColumnTypes, _)),
                each {_, Record.Field(ColumnTypes, _)}
            ), "en-US")
      in Typed
in
    // Query names must stay aligned with powerbi/lending_dashboard_model.json
    // and the dbt-produced BI/export contract. Power BI should not load raw files.
    [
        bi_executive_overview = LoadCsv("bi_executive_overview"),
        bi_state_lending_trends = LoadCsv("bi_state_lending_trends"),
        bi_lender_concentration = LoadCsv("bi_lender_concentration"),
        bi_industry_mix = LoadCsv("bi_industry_mix"),
        bi_program_mix = LoadCsv("bi_program_mix"),
        bi_regional_business_health = LoadCsv("bi_regional_business_health"),
        bi_pipeline_health = LoadCsv("bi_pipeline_health"),
        bi_source_freshness = LoadCsv("bi_source_freshness"),
        bi_lender_mix = LoadCsv("bi_lender_mix"),
        bi_lending_performance = LoadCsv("bi_lending_performance"),
        bi_lending_status_mix = LoadCsv("bi_lending_status_mix"),
        bi_lending_terms_pricing = LoadCsv("bi_lending_terms_pricing"),
        bi_lending_jobs_impact = LoadCsv("bi_lending_jobs_impact"),
        bi_state_filter = LoadCsv("bi_state_filter"),
        bi_year_filter = LoadCsv("bi_year_filter"),
        bi_loan_program_filter = LoadCsv("bi_loan_program_filter"),
        bi_naics_filter = LoadCsv("bi_naics_filter"),
        bi_lender_filter = LoadCsv("bi_lender_filter")
    ]
